//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string AdminId { get; set; }
        public string AdminName { get; set; }
        public Nullable<bool> Super { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> PendingRequests { get; set; }
    }
}
