//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerMapGuidance
    {
        public CareerMapGuidance()
        {
            this.CareerMapAlternatives = new HashSet<CareerMapAlternative>();
        }
    
        public string TitleJobId { get; set; }
        public string ParentJobTitleId { get; set; }
        public string TitlejobFamily { get; set; }
        public string PostUserID { get; set; }
        public System.DateTime PostDate { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUserID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<CareerMapAlternative> CareerMapAlternatives { get; set; }
    }
}
