//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatSetting
    {
        public decimal ChatID { get; set; }
        public System.DateTime ChatStartTime { get; set; }
        public System.DateTime ChatEndTime { get; set; }
        public string ChatOccurance { get; set; }
    }
}
