//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptDef
    {
        public decimal ConceptDefID { get; set; }
        public int LanguageID { get; set; }
        public string ConceptDefTitle { get; set; }
        public string ConceptDefDesc { get; set; }
        public string PostUserId { get; set; }
        public System.DateTime PostDate { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUserID { get; set; }
    }
}
