//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigCenter
    {
        public string Key { get; set; }
        public string Value { get; set; }
        public int TextType { get; set; }
        public int SexCode { get; set; }
        public int CategoryType { get; set; }
    }
}
