//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTheme
    {
        public DimTheme()
        {
            this.Reports = new HashSet<Report>();
            this.ThemesVariables = new HashSet<ThemesVariable>();
        }
    
        public int CodeNo { get; set; }
        public string NameFr { get; set; }
        public string NameAr { get; set; }
        public string Name { get; set; }
        public string ThemeType { get; set; }
        public string UnitScaleFr { get; set; }
        public string UnitScaleAr { get; set; }
        public string UnitScale { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<ThemesVariable> ThemesVariables { get; set; }
    }
}
