//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsDetail
    {
        public decimal EventId { get; set; }
        public int LanguageID { get; set; }
        public string EventTitle { get; set; }
        public string EventAddress { get; set; }
        public string EventContactAddress { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
