//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public decimal FAQID { get; set; }
        public string FAQCategoryID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.DateTime PostDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PostUserID { get; set; }
        public string UpdateUserID { get; set; }
        public string DeleteUserID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public int FAQLanguage { get; set; }
    }
}
