//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralCode
    {
        public GeneralCode()
        {
            this.SubCodes = new HashSet<SubCode>();
        }
    
        public string GeneralID { get; set; }
        public string Name { get; set; }
        public Nullable<byte> InternalCode { get; set; }
        public string ParentGeneralcodeID { get; set; }
        public int LanguageID { get; set; }
    
        public virtual ICollection<SubCode> SubCodes { get; set; }
    }
}
