//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualEducationlevelDet
    {
        public decimal IndividualEducationlevelID { get; set; }
        public int LanguageID { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionType { get; set; }
        public string CertificationType { get; set; }
        public string FacultyName { get; set; }
        public string Grade { get; set; }
    
        public virtual IndividualEducationlevel IndividualEducationlevel { get; set; }
    }
}
