//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualExperienceDetail
    {
        public IndividualExperienceDetail()
        {
            this.IndividualExperienceDetails_Det = new HashSet<IndividualExperienceDetails_Det>();
        }
    
        public decimal IndividualExperienceID { get; set; }
        public decimal PortalUsersID { get; set; }
        public System.DateTime EmploymentStartDate { get; set; }
        public Nullable<System.DateTime> EmploymentEndDate { get; set; }
        public string EmploymentJobTitle { get; set; }
        public string TypeOfEmployment { get; set; }
        public byte CurrentEmploymentStatus { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PostUserID { get; set; }
        public string UpdateUserID { get; set; }
        public string DeleteUserID { get; set; }
        public int ExpYears { get; set; }
        public int ExpMonths { get; set; }
    
        public virtual IndividualDetail IndividualDetail { get; set; }
        public virtual ICollection<IndividualExperienceDetails_Det> IndividualExperienceDetails_Det { get; set; }
    }
}
