//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualTrainingDetail
    {
        public IndividualTrainingDetail()
        {
            this.IndividualTrainingDetails_Det = new HashSet<IndividualTrainingDetails_Det>();
        }
    
        public decimal IndividualTrainingID { get; set; }
        public decimal PortalUsersID { get; set; }
        public System.DateTime TrainingStartDate { get; set; }
        public System.DateTime TrainingEndDate { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PostUserID { get; set; }
        public string UpdateUserID { get; set; }
        public string DeleteUserID { get; set; }
    
        public virtual IndividualDetail IndividualDetail { get; set; }
        public virtual ICollection<IndividualTrainingDetails_Det> IndividualTrainingDetails_Det { get; set; }
    }
}
