//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualEducationlevel
    {
        public IndividualEducationlevel()
        {
            this.IndividualEducationlevelDets = new HashSet<IndividualEducationlevelDet>();
        }
    
        public decimal IndividualEducationlevelID { get; set; }
        public decimal PortalUsersID { get; set; }
        public string LevelOfEducation { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public string UpdateUserID { get; set; }
        public string DeleteUserID { get; set; }
        public int GraduationYear { get; set; }
        public Nullable<double> GradePrecentage { get; set; }
        public Nullable<double> GradeGPA { get; set; }
        public string Degree { get; set; }
    
        public virtual IndividualDetail IndividualDetail { get; set; }
        public virtual ICollection<IndividualEducationlevelDet> IndividualEducationlevelDets { get; set; }
    }
}
