//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualExperienceDetails_Det
    {
        public decimal IndividualExperienceID { get; set; }
        public int LanguageID { get; set; }
        public string EmployerName { get; set; }
        public string EmploymentJobDescription { get; set; }
    
        public virtual IndividualExperienceDetail IndividualExperienceDetail { get; set; }
    }
}
