//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualDetail
    {
        public IndividualDetail()
        {
            this.IndividualCertificationDetails = new HashSet<IndividualCertificationDetail>();
            this.IndividualDetailsDets = new HashSet<IndividualDetailsDet>();
            this.IndividualOtherSkills = new HashSet<IndividualOtherSkill>();
            this.IndividualSkillsDetails = new HashSet<IndividualSkillsDetail>();
            this.JobApplieds = new HashSet<JobApplied>();
            this.TrainingApplies = new HashSet<TrainingApply>();
            this.IndividualEducationlevels = new HashSet<IndividualEducationlevel>();
            this.IndividualExperienceDetails = new HashSet<IndividualExperienceDetail>();
            this.IndividualTrainingDetails = new HashSet<IndividualTrainingDetail>();
            this.IndividualSkillsDetails_Delete = new HashSet<IndividualSkillsDetails_Delete>();
        }
    
        public decimal PortalUsersID { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string GenderId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MaritalStatusId { get; set; }
        public string MilitaryStatus_Id { get; set; }
        public string NationalityId { get; set; }
        public string PhotoPath { get; set; }
        public byte Is_Approved { get; set; }
        public byte AllowtoViewMyInfo { get; set; }
        public string RejectReason { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string PostUserID { get; set; }
        public string UpdateUserID { get; set; }
        public string IndividualMedicalID { get; set; }
        public string UserID { get; set; }
        public string CountryID { get; set; }
        public string CityID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<IndividualCertificationDetail> IndividualCertificationDetails { get; set; }
        public virtual ICollection<IndividualDetailsDet> IndividualDetailsDets { get; set; }
        public virtual ICollection<IndividualOtherSkill> IndividualOtherSkills { get; set; }
        public virtual ICollection<IndividualSkillsDetail> IndividualSkillsDetails { get; set; }
        public virtual ICollection<JobApplied> JobApplieds { get; set; }
        public virtual ICollection<TrainingApply> TrainingApplies { get; set; }
        public virtual ICollection<IndividualEducationlevel> IndividualEducationlevels { get; set; }
        public virtual ICollection<IndividualExperienceDetail> IndividualExperienceDetails { get; set; }
        public virtual ICollection<IndividualTrainingDetail> IndividualTrainingDetails { get; set; }
        public virtual ICollection<IndividualSkillsDetails_Delete> IndividualSkillsDetails_Delete { get; set; }
        public virtual PortalUser PortalUser { get; set; }
    }
}
