//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOfferEducationLevel
    {
        public JobOfferEducationLevel()
        {
            this.JobOfferEducationLevelDetails = new HashSet<JobOfferEducationLevelDetail>();
        }
    
        public decimal JobOfferID { get; set; }
        public string EducationLevelID { get; set; }
        public string EducationCertificationType { get; set; }
    
        public virtual JobOffer JobOffer { get; set; }
        public virtual ICollection<JobOfferEducationLevelDetail> JobOfferEducationLevelDetails { get; set; }
    }
}
