//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobOfferSkillsDetail
    {
        public decimal jobOfferSkillsDetailsID { get; set; }
        public decimal JobOfferID { get; set; }
        public string SkillID { get; set; }
        public string SkillLevelID { get; set; }
        public string YearsOf_Experience { get; set; }
        public string SkillTypeID { get; set; }
        public string IndustryID { get; set; }
    
        public virtual JobOffer JobOffer { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
