//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeekersGuidancekit
    {
        public JobSeekersGuidancekit()
        {
            this.JobSeekersGuidancekitDetails = new HashSet<JobSeekersGuidancekitDetail>();
        }
    
        public int JobSeekerGuidanceID { get; set; }
        public string JobSeekerGuidanceType { get; set; }
        public string URL { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string PostUserID { get; set; }
        public string UpdateUserID { get; set; }
    
        public virtual ICollection<JobSeekersGuidancekitDetail> JobSeekersGuidancekitDetails { get; set; }
    }
}
