//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobseekerTemplate
    {
        public JobseekerTemplate()
        {
            this.JobseekerTemplatesDetails = new HashSet<JobseekerTemplatesDetail>();
        }
    
        public int JobseekerTemplateID { get; set; }
        public string TemplateType { get; set; }
        public string TemplateFilePath { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserID { get; set; }
        public string PostUserID { get; set; }
    
        public virtual ICollection<JobseekerTemplatesDetail> JobseekerTemplatesDetails { get; set; }
    }
}
