//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewHire
    {
        public decimal NewHireID { get; set; }
        public decimal PortalUserID { get; set; }
        public string NewHireIdType { get; set; }
        public string NewHireIDNumber { get; set; }
        public Nullable<decimal> JobOfferId { get; set; }
        public Nullable<decimal> IndvPortalUserId { get; set; }
    
        public virtual OrganizationDetail OrganizationDetail { get; set; }
    }
}
