//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public decimal NewsID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDescription { get; set; }
        public System.DateTime NewsDate { get; set; }
        public System.DateTime NewsExpiryDate { get; set; }
        public string NewsBannerPath { get; set; }
        public string NewsIconPath { get; set; }
        public string NewsVideoPath { get; set; }
        public int NewsLangauage { get; set; }
        public string PostUserID { get; set; }
        public System.DateTime PostDate { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUserID { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public bool IsInformal { get; set; }
        public bool IsAchievement { get; set; }
    }
}
