//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewTrainee
    {
        public decimal NewTraineeID { get; set; }
        public decimal PortalUserID { get; set; }
        public string NewTraineeIdType { get; set; }
        public string NewTraineeIDNumber { get; set; }
        public Nullable<decimal> TrainingOfferId { get; set; }
        public Nullable<decimal> IndPortalUserId { get; set; }
    
        public virtual OrganizationDetail OrganizationDetail { get; set; }
    }
}
