//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeDetail
    {
        public decimal OfficeID { get; set; }
        public int LangID { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
    
        public virtual Office Office { get; set; }
    }
}
