//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunity
    {
        public Opportunity()
        {
            this.OpportunitiesDetails = new HashSet<OpportunitiesDetail>();
        }
    
        public decimal OpportunityID { get; set; }
        public decimal OrganizationContactID { get; set; }
        public string OpportunityFilePath { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public byte Is_Approved { get; set; }
        public string RejectReason { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUserID { get; set; }
        public bool IsInformal { get; set; }
        public Nullable<bool> IsInternal { get; set; }
    
        public virtual OrganizationContact_Info OrganizationContact_Info { get; set; }
        public virtual ICollection<OpportunitiesDetail> OpportunitiesDetails { get; set; }
    }
}
