//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationContactInfoDetail
    {
        public decimal OrganizationContactID { get; set; }
        public int LanguageID { get; set; }
        public string ContactFullName { get; set; }
        public string Department { get; set; }
    
        public virtual OrganizationContact_Info OrganizationContact_Info { get; set; }
    }
}
