//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationContact_Info
    {
        public OrganizationContact_Info()
        {
            this.Events = new HashSet<Event>();
            this.Opportunities = new HashSet<Opportunity>();
            this.OrganizationContactInfoDetails = new HashSet<OrganizationContactInfoDetail>();
        }
    
        public decimal OrganizationContactID { get; set; }
        public decimal PortalUsersID { get; set; }
        public string JobTitleID { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string AuthorizationletterPath { get; set; }
        public byte IsApproved { get; set; }
        public string RejectReason { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string PostUSerID { get; set; }
        public string UpdateUSerID { get; set; }
        public string DeleteUserID { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual OrganizationDetail OrganizationDetail { get; set; }
        public virtual ICollection<OrganizationContactInfoDetail> OrganizationContactInfoDetails { get; set; }
    }
}
