//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.PagesActions = new HashSet<PagesAction>();
        }
    
        public int id { get; set; }
        public string Page1 { get; set; }
        public string Path { get; set; }
        public string PageCode { get; set; }
    
        public virtual ICollection<PagesAction> PagesActions { get; set; }
    }
}
