//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersDetail
    {
        public decimal PartnerID { get; set; }
        public int LanguageID { get; set; }
        public string CEOFirstName { get; set; }
        public string CEOLastName { get; set; }
        public string GeneralDescriptionCoreBusiness { get; set; }
        public string PossibleAreaOfCooperation { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
