//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalUser
    {
        public decimal PortalUsersID { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string UserCategory { get; set; }
        public string UserSubCategory { get; set; }
        public bool TrainingProvider { get; set; }
        public bool Employer { get; set; }
        public bool JobSeeker { get; set; }
        public bool TrainingSeeker { get; set; }
        public bool Researcher { get; set; }
        public bool Internal { get; set; }
        public bool IsSubscriper { get; set; }
    
        public virtual IndividualDetail IndividualDetail { get; set; }
        public virtual OrganizationDetail OrganizationDetail { get; set; }
    }
}
