//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.IndividualSkillsDetails = new HashSet<IndividualSkillsDetail>();
            this.jobOfferSkillsDetails = new HashSet<jobOfferSkillsDetail>();
            this.TrainingSkillDetails = new HashSet<TrainingSkillDetail>();
        }
    
        public string SkillID { get; set; }
        public string UnitID { get; set; }
        public string IndustryId { get; set; }
        public string SkillLevel_ID { get; set; }
    
        public virtual ICollection<IndividualSkillsDetail> IndividualSkillsDetails { get; set; }
        public virtual ICollection<jobOfferSkillsDetail> jobOfferSkillsDetails { get; set; }
        public virtual ICollection<TrainingSkillDetail> TrainingSkillDetails { get; set; }
    }
}
