//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCode
    {
        public string SubID { get; set; }
        public string GeneralID { get; set; }
        public int LanguageID { get; set; }
        public string Name { get; set; }
        public string ParentSubCodeID { get; set; }
    
        public virtual GeneralCode GeneralCode { get; set; }
        public virtual Langauge Langauge { get; set; }
    }
}
