//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public Testimonial()
        {
            this.TestimonialsDetails = new HashSet<TestimonialsDetail>();
        }
    
        public decimal TestimonialID { get; set; }
        public int PortalUserID { get; set; }
        public int SiteRating { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeleteReason { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public byte IsApproved { get; set; }
    
        public virtual ICollection<TestimonialsDetail> TestimonialsDetails { get; set; }
    }
}
