//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestimonialsDetail
    {
        public decimal TestimonialID { get; set; }
        public int LanguageID { get; set; }
        public string Comments { get; set; }
    
        public virtual Testimonial Testimonial { get; set; }
    }
}
