//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingOfferDetail
    {
        public decimal TrainingOfferID { get; set; }
        public int LanguageID { get; set; }
        public string CourseDescription { get; set; }
        public string OtherCours_Name { get; set; }
        public string Address { get; set; }
    
        public virtual TrainingOffer TrainingOffer { get; set; }
    }
}
