//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingApply
    {
        public decimal TrainingAppliedID { get; set; }
        public decimal TrainingOfferID { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public int ViewStatus { get; set; }
        public decimal IndPortalUserID { get; set; }
    
        public virtual IndividualDetail IndividualDetail { get; set; }
        public virtual TrainingOffer TrainingOffer { get; set; }
    }
}
