//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingOffer
    {
        public TrainingOffer()
        {
            this.TrainingApplies = new HashSet<TrainingApply>();
            this.TrainingOfferDetails = new HashSet<TrainingOfferDetail>();
            this.TrainingOfferOccurrences = new HashSet<TrainingOfferOccurrence>();
            this.TrainingOtherSkills = new HashSet<TrainingOtherSkill>();
            this.TrainingSkillDetails = new HashSet<TrainingSkillDetail>();
        }
    
        public decimal TrainingOfferID { get; set; }
        public decimal PortalUsersID { get; set; }
        public decimal OrganizationContactID { get; set; }
        public string CourseNameID { get; set; }
        public int CourseDurationPerDay { get; set; }
        public System.DateTime CourseTimeFrom { get; set; }
        public System.DateTime CourseTimeTo { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public Nullable<double> CourseCost { get; set; }
        public byte Is_Approved { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string RejectReason { get; set; }
        public string CountryID { get; set; }
        public string CityID { get; set; }
        public string PostUSerID { get; set; }
        public string UpdateUSerID { get; set; }
        public string DeleteUserID { get; set; }
        public bool trainingStatus { get; set; }
        public string OutlineFile { get; set; }
    
        public virtual OrganizationDetail OrganizationDetail { get; set; }
        public virtual ICollection<TrainingApply> TrainingApplies { get; set; }
        public virtual ICollection<TrainingOfferDetail> TrainingOfferDetails { get; set; }
        public virtual ICollection<TrainingOfferOccurrence> TrainingOfferOccurrences { get; set; }
        public virtual ICollection<TrainingOtherSkill> TrainingOtherSkills { get; set; }
        public virtual ICollection<TrainingSkillDetail> TrainingSkillDetails { get; set; }
    }
}
