//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionCommittee
    {
        public UnionCommittee()
        {
            this.UnionCommitteeDetails = new HashSet<UnionCommitteeDetail>();
        }
    
        public decimal UnionID { get; set; }
        public int ComID { get; set; }
        public string Gov { get; set; }
    
        public virtual ICollection<UnionCommitteeDetail> UnionCommitteeDetails { get; set; }
        public virtual Union Union { get; set; }
    }
}
