//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionProfession
    {
        public decimal UnionID { get; set; }
        public int ProfID { get; set; }
        public int LangID { get; set; }
        public string Name { get; set; }
    
        public virtual Union Union { get; set; }
    }
}
