//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMIS.Dal.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariablesMapping
    {
        public int ID { get; set; }
        public string VariableID { get; set; }
        public string ColumnName { get; set; }
        public string QueryColumn { get; set; }
        public string QueryFrom { get; set; }
        public string VariableColumnName { get; set; }
        public string VariableENName { get; set; }
    }
}
