//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MessagesResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the entered work office data are incomplete..
        /// </summary>
        internal static string B001_Error1 {
            get {
                return ResourceManager.GetString("B001_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new committee ....
        /// </summary>
        internal static string B002_AddComm {
            get {
                return ResourceManager.GetString("B002_AddComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new profession ....
        /// </summary>
        internal static string B002_AddProf {
            get {
                return ResourceManager.GetString("B002_AddProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the entered labour union data are incomplete..
        /// </summary>
        internal static string B002_Error1 {
            get {
                return ResourceManager.GetString("B002_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span style=&quot;color: green; font-weight: bolder&quot;&gt;Green&lt;/span&gt; specifies a search result that matches a search criteria.&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;color: red; font-weight: bolder&quot;&gt;Red&lt;/span&gt; specifies a search result that does NOT match a search criteria.&lt;/p&gt;.
        /// </summary>
        internal static string F003_ColorCode {
            get {
                return ResourceManager.GetString("F003_ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ + Insert a new job title ].
        /// </summary>
        internal static string F004_AddJobTitle {
            get {
                return ResourceManager.GetString("F004_AddJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the entered job data are incomplete..
        /// </summary>
        internal static string F004_Error1 {
            get {
                return ResourceManager.GetString("F004_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date &lt; Today, or End Date &lt; Start Date.
        /// </summary>
        internal static string F004_Error2 {
            get {
                return ResourceManager.GetString("F004_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This job has already been posted before..
        /// </summary>
        internal static string F004_Error3 {
            get {
                return ResourceManager.GetString("F004_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for new applications.
        /// </summary>
        internal static string F004_JobIsOpen {
            get {
                return ResourceManager.GetString("F004_JobIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applicants to display ....
        /// </summary>
        internal static string F004_NoApplicants {
            get {
                return ResourceManager.GetString("F004_NoApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity title is not of proper length..
        /// </summary>
        internal static string F005_Error1 {
            get {
                return ResourceManager.GetString("F005_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date &lt; Today, or End Date &lt; Start Date.
        /// </summary>
        internal static string F005_Error2 {
            get {
                return ResourceManager.GetString("F005_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This opportunity has already been posted for the same start date..
        /// </summary>
        internal static string F005_Error3 {
            get {
                return ResourceManager.GetString("F005_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title, Opportunity Image File, Start Date, End Date.
        /// </summary>
        internal static string F005_RequiredFields {
            get {
                return ResourceManager.GetString("F005_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating entered opportunity data..
        /// </summary>
        internal static string F005_Step1 {
            get {
                return ResourceManager.GetString("F005_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving opportunity to database..
        /// </summary>
        internal static string F005_Step3 {
            get {
                return ResourceManager.GetString("F005_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the entered event data are incomplete..
        /// </summary>
        internal static string F006_Error1 {
            get {
                return ResourceManager.GetString("F006_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date &lt; Today, or End Date &lt; Start Date.
        /// </summary>
        internal static string F006_Error2 {
            get {
                return ResourceManager.GetString("F006_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event has already been posted for the same start date..
        /// </summary>
        internal static string F006_Error3 {
            get {
                return ResourceManager.GetString("F006_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format for contact website..
        /// </summary>
        internal static string F006_InvalidUrl {
            get {
                return ResourceManager.GetString("F006_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title, Start Date, End Date, Address, Type, Price, Contact Information and Event File.
        /// </summary>
        internal static string F006_RequiredFields {
            get {
                return ResourceManager.GetString("F006_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating entered event data..
        /// </summary>
        internal static string F006_Step1 {
            get {
                return ResourceManager.GetString("F006_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving event to database..
        /// </summary>
        internal static string F006_Step3 {
            get {
                return ResourceManager.GetString("F006_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        internal static string F007_InvalidLogin {
            get {
                return ResourceManager.GetString("F007_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockedOut.
        /// </summary>
        internal static string F007_LockedOut {
            get {
                return ResourceManager.GetString("F007_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Verification.
        /// </summary>
        internal static string F007_RequiresVerification {
            get {
                return ResourceManager.GetString("F007_RequiresVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must equel Re-type Password.
        /// </summary>
        internal static string F009_Confirmation_Password_and_ConfirmationPassword {
            get {
                return ResourceManager.GetString("F009_Confirmation_Password_and_ConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        internal static string F009_Employer {
            get {
                return ResourceManager.GetString("F009_Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname, Lastname, Email, Password, Retypepassword, NationalID, Military, Gender, Nationailty,Medical Conditions, Country, City and IDType.
        /// </summary>
        internal static string F009_RequiredFieldsstep1 {
            get {
                return ResourceManager.GetString("F009_RequiredFieldsstep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Enter at least one Record.
        /// </summary>
        internal static string F009_RequiredFieldsstep2 {
            get {
                return ResourceManager.GetString("F009_RequiredFieldsstep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course is open for new applications ....
        /// </summary>
        internal static string F015_CourseIsOpen {
            get {
                return ResourceManager.GetString("F015_CourseIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the entered training offer data are incomplete..
        /// </summary>
        internal static string F015_Error1 {
            get {
                return ResourceManager.GetString("F015_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date &lt; Today, or End Date &lt; Start Date.
        /// </summary>
        internal static string F015_Error2 {
            get {
                return ResourceManager.GetString("F015_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (to) &lt; Time (from).
        /// </summary>
        internal static string F015_Error3 {
            get {
                return ResourceManager.GetString("F015_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applicants to display ....
        /// </summary>
        internal static string F015_NoApplicants {
            get {
                return ResourceManager.GetString("F015_NoApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied to this training course before..
        /// </summary>
        internal static string F021_Error1 {
            get {
                return ResourceManager.GetString("F021_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t meet the job requirements..
        /// </summary>
        internal static string F022_Error1 {
            get {
                return ResourceManager.GetString("F022_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied to this job before..
        /// </summary>
        internal static string F022_Error2 {
            get {
                return ResourceManager.GetString("F022_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide all files..
        /// </summary>
        internal static string F022_SelectAllFiles {
            get {
                return ResourceManager.GetString("F022_SelectAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found.
        /// </summary>
        internal static string F026_NoUser {
            get {
                return ResourceManager.GetString("F026_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        internal static string F026_passwordChanged {
            get {
                return ResourceManager.GetString("F026_passwordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to approve this record ?.
        /// </summary>
        internal static string F033_ConfirmApproval {
            get {
                return ResourceManager.GetString("F033_ConfirmApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reason for rejection ....
        /// </summary>
        internal static string F033_ConfirmRejection {
            get {
                return ResourceManager.GetString("F033_ConfirmRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot approve this request before you finish editing the record..
        /// </summary>
        internal static string F033_FinishEditing {
            get {
                return ResourceManager.GetString("F033_FinishEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign to another admin.
        /// </summary>
        internal static string F033_ReassignAdmin {
            get {
                return ResourceManager.GetString("F033_ReassignAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have verified all attachments and/or detected obscene words..
        /// </summary>
        internal static string F033_ReviewComplete {
            get {
                return ResourceManager.GetString("F033_ReviewComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can approve this request, you need to verify all attachments and/or detected obscene words using the &quot;Reviews&quot; tab..
        /// </summary>
        internal static string F033_ReviewsRequired {
            get {
                return ResourceManager.GetString("F033_ReviewsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Variables do not have values.
        /// </summary>
        internal static string F11_ReportVariableNoData {
            get {
                return ResourceManager.GetString("F11_ReportVariableNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete registration data. Please fill all mandatory fields..
        /// </summary>
        internal static string R001_Error1 {
            get {
                return ResourceManager.GetString("R001_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long and contain 3 of the following 4 items: upper case letters, lower case letters, symbols and numbers.
        /// </summary>
        internal static string W001_InvalidPassword {
            get {
                return ResourceManager.GetString("W001_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords mismatch.
        /// </summary>
        internal static string W001_PasswordsMismatch {
            get {
                return ResourceManager.GetString("W001_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already registered.
        /// </summary>
        internal static string W001_RegisteredEmail {
            get {
                return ResourceManager.GetString("W001_RegisteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d like to use this portal to post job offers..
        /// </summary>
        internal static string W003_OfferJobs {
            get {
                return ResourceManager.GetString("W003_OfferJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d like to use this portal to post training offers..
        /// </summary>
        internal static string W003_OfferTraining {
            get {
                return ResourceManager.GetString("W003_OfferTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d like to use this portal to find training offers for our staff..
        /// </summary>
        internal static string W003_ReceiveTraining {
            get {
                return ResourceManager.GetString("W003_ReceiveTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the services your organization may offer/receive:.
        /// </summary>
        internal static string W003_SelectServices {
            get {
                return ResourceManager.GetString("W003_SelectServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post has been approved by system admin..
        /// </summary>
        internal static string X_Approved {
            get {
                return ResourceManager.GetString("X_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from the list ....
        /// </summary>
        internal static string X_ChooseFromDDL {
            get {
                return ResourceManager.GetString("X_ChooseFromDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        internal static string X_ConfirmContinue {
            get {
                return ResourceManager.GetString("X_ConfirmContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/mm/yy.
        /// </summary>
        internal static string X_DatePickerDate {
            get {
                return ResourceManager.GetString("X_DatePickerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Server&apos;s Version of the File.
        /// </summary>
        internal static string X_DownloadServerFile {
            get {
                return ResourceManager.GetString("X_DownloadServerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to execute this function..
        /// </summary>
        internal static string X_Error101 {
            get {
                return ResourceManager.GetString("X_Error101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error when verifying uploaded file(s)..
        /// </summary>
        internal static string X_Error102 {
            get {
                return ResourceManager.GetString("X_Error102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Record In Relation.
        /// </summary>
        internal static string X_Error103_InRelation {
            get {
                return ResourceManager.GetString("X_Error103_InRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item Exist Before.
        /// </summary>
        internal static string X_Exist {
            get {
                return ResourceManager.GetString("X_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file(s) {0}.
        /// </summary>
        internal static string X_FileUpload {
            get {
                return ResourceManager.GetString("X_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file(s) {0}: {1} %.
        /// </summary>
        internal static string X_FileUploadProgress {
            get {
                return ResourceManager.GetString("X_FileUploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time Must be Less ThanTo Time.
        /// </summary>
        internal static string X_FromGreateThanToTime {
            get {
                return ResourceManager.GetString("X_FromGreateThanToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/mm/yyyy.
        /// </summary>
        internal static string X_InputMaskDate {
            get {
                return ResourceManager.GetString("X_InputMaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ + Insert a new item ].
        /// </summary>
        internal static string X_InsertNewItem {
            get {
                return ResourceManager.GetString("X_InsertNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        internal static string X_InvalidEmail {
            get {
                return ResourceManager.GetString("X_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved file is not accepted..
        /// </summary>
        internal static string X_InvalidFile {
            get {
                return ResourceManager.GetString("X_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file. Please choose a file of extension {0} and a max size of {1} MB..
        /// </summary>
        internal static string X_InvalidFileForUpload {
            get {
                return ResourceManager.GetString("X_InvalidFileForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields marked by an asterisk *.
        /// </summary>
        internal static string X_MarkedRequiredFields {
            get {
                return ResourceManager.GetString("X_MarkedRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Reach max Length.
        /// </summary>
        internal static string X_MaxLength {
            get {
                return ResourceManager.GetString("X_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD/MM/YYYY.
        /// </summary>
        internal static string X_MomentDate {
            get {
                return ResourceManager.GetString("X_MomentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not authorized..
        /// </summary>
        internal static string X_NotAuthorized {
            get {
                return ResourceManager.GetString("X_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has failed..
        /// </summary>
        internal static string X_OperationFailure {
            get {
                return ResourceManager.GetString("X_OperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successful..
        /// </summary>
        internal static string X_OperationSuccess {
            get {
                return ResourceManager.GetString("X_OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sory, This link Expired.
        /// </summary>
        internal static string X_PasswordResetedLinkExpired {
            get {
                return ResourceManager.GetString("X_PasswordResetedLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post is pending system admin review for approval..
        /// </summary>
        internal static string X_Pending {
            get {
                return ResourceManager.GetString("X_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing your request..
        /// </summary>
        internal static string X_Processing {
            get {
                return ResourceManager.GetString("X_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This post has been rejected by system admin for the following reason:.
        /// </summary>
        internal static string X_Rejected {
            get {
                return ResourceManager.GetString("X_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string X_Required {
            get {
                return ResourceManager.GetString("X_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields are required:.
        /// </summary>
        internal static string X_RequiredFieldErrors {
            get {
                return ResourceManager.GetString("X_RequiredFieldErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Review Your Email.
        /// </summary>
        internal static string X_ReviewEmail {
            get {
                return ResourceManager.GetString("X_ReviewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving records to database ....
        /// </summary>
        internal static string X_Saving {
            get {
                return ResourceManager.GetString("X_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image file....
        /// </summary>
        internal static string X_SelectAnImage {
            get {
                return ResourceManager.GetString("X_SelectAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an video file....
        /// </summary>
        internal static string X_SelectAnVideo {
            get {
                return ResourceManager.GetString("X_SelectAnVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file....
        /// </summary>
        internal static string X_SelectFile {
            get {
                return ResourceManager.GetString("X_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select skills ....
        /// </summary>
        internal static string X_SelectSkills {
            get {
                return ResourceManager.GetString("X_SelectSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string X_Success {
            get {
                return ResourceManager.GetString("X_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string X_Training {
            get {
                return ResourceManager.GetString("X_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص العربي.
        /// </summary>
        internal static string X_TypeInArabic {
            get {
                return ResourceManager.GetString("X_TypeInArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English text.
        /// </summary>
        internal static string X_TypeInEnglish {
            get {
                return ResourceManager.GetString("X_TypeInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texte français.
        /// </summary>
        internal static string X_TypeInFrench {
            get {
                return ResourceManager.GetString("X_TypeInFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to leave this page without saving?.
        /// </summary>
        internal static string X_UnsavedChanges {
            get {
                return ResourceManager.GetString("X_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported media type..
        /// </summary>
        internal static string X_UnsupportedMediaType {
            get {
                return ResourceManager.GetString("X_UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating entered data ....
        /// </summary>
        internal static string X_Validating {
            get {
                return ResourceManager.GetString("X_Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process your request:.
        /// </summary>
        internal static string X_ValidationErrors {
            get {
                return ResourceManager.GetString("X_ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        internal static string X_Warning {
            get {
                return ResourceManager.GetString("X_Warning", resourceCulture);
            }
        }
    }
}
